project:
  name: Demo - Bank Customer Support
  id: demo-bank-customer-support
  description: Demo project

tasks:
  - input: "How do I reset my internet banking password?"
    checklist: |-
      - Verify that the answer explains the steps to reset the internet banking password.
      - Check if the answer mentions that users who have verified their mobile number can reset the password online through internet banking or the mobile app.
      - Ensure that the answer notes an SMS one-time code will be sent, and the user needs to answer their KeepSafe questions.
      - Confirm that it informs users without a registered mobile number to call Kiwibank with their access number and ID used when opening the account.
      - Verify that the answer advises users to verify their mobile number during the call for future self-service password resets.
    min_score: 1

  # - input: "How can I update my registered mobile number?"
  #   checklist: |-
  #     - Verify that the answer explains that users can update their mobile number in internet banking or the mobile app by following specific instructions.
  #     - Check if the answer mentions that users experiencing technical problems accessing their account online should contact Kiwibank.
  #     - Ensure that it states users will need to provide their access number and the ID used to open their account.
  #     - Confirm that the answer notes they only get five free calls per month and that fees may apply after that.
  #   min_score: 1

  # - input: "How do I set up payments for online shopping?"
  #   checklist: |-
  #     - Verify that the answer explains how to set up payments for online shopping.
  #     - Check if it advises users to enter their card details on the payment page of the online store.
  #     - Ensure that the answer emphasizes checking for the locked padlock icon in the browser before the website address to confirm it's a secure site.
  #     - Confirm that it suggests users regularly check their accounts to ensure the correct amounts are going out at the right time.
  #     - Verify that the answer references staying safe when making payments online, such as directing users to the security page.
  #   min_score: 1

  # - input: "How do I activate my credit card if I don't have internet banking?"
  #   checklist: |-
  #     - Verify that the answer explains how to activate a credit card without internet banking.
  #     - If the card already has a PIN:
  #       - Check if the answer advises the user to activate the card by using it in any store, inserting the card into the EFTPOS machine, and entering their current PIN.
  #     - If the card doesn't have a PIN:
  #       - Ensure that the answer informs the user they can activate the card by making a purchase in-store and signing for it.
  #       - Confirm that it mentions after making a purchase by signing, the user will be able to make contactless payments.
  #       - Verify that it notes the user won't be able to use the card in an ATM without a PIN.
  #     - Check if the answer suggests calling Kiwibank or visiting the nearest branch to activate the card or set a PIN.
  #   min_score: 1

  # - input: "How do I change my maturity instructions for my Term Deposit?"
  #   checklist: |-
  #     - Verify that the answer explains how to change maturity instructions in internet banking.
  #     - Check that the answer provides step-by-step guidance:
  #       - Select the Term Deposit on the 'Accounts' page.
  #       - Select 'Change' next to Maturity details.
  #     - Ensure that the answer describes the options available:
  #       - Change to pay out the interest at maturity to a New Zealand dollar bank account.
  #       - Change to pay out the full Term Deposit at maturity to a New Zealand dollar bank account.
  #       - Reinvest the Term Deposit with or without the interest by choosing the term to reinvest.
  #     - Confirm that it mentions if the user chooses to reinvest at maturity, the Term Deposit will reinvest for the selected term at the rate on the day of maturity.
  #     - Verify that the explanation is clear and complete.
  #   min_score: 1

  # - input: "How do I apply for a home loan with Kiwibank?"
  #   checklist: |-
  #     - Verify that the answer correctly recognizes that the information is not available in the provided document.
  #     - Check that the response politely informs the user that this information isn't covered in the current context.
  #     - Ensure that it suggests visiting the Kiwibank website or contacting customer support for assistance with home loans.
  #     - Confirm that the answer avoids providing incorrect or fabricated information.
  #     - Verify that the response is appropriate, helpful, and adheres to policies on handling unsupported queries.
  #   min_score: 1
